/* gen_map.c — HOST-ONLY. Emits src/map_data.c (the initial 4x4 world map) to
 * stdout. Run from gen.sh; the result is committed and compiled into the wasm.
 * The map is fully determined at authoring time, so it is baked as data, not
 * built at runtime.
 *
 * Each screen-grid gets solid borders with a one-cell gap at the centre of each
 * side, plus the central cross (row 7 / col 10) kept open so all four gaps
 * connect within the screen, plus a few interior blocks (varied per screen) to
 * make the within-screen routing non-trivial. The centre gaps line up across
 * every inner screen border and across the outer wrap, connecting the world. */
#include <stdio.h>
#include "../src/defs.h"

static uint32_t g[N_SCREENS][GRID_H];

static void wall(uint32_t s, int cx, int cy) { g[s][cy] |= (1u << cx); }
static void open_(uint32_t s, int cx, int cy) { g[s][cy] &= ~(1u << cx); }
static void hbar(uint32_t s, int c0, int c1, int cy) { for (int c = c0; c <= c1; c++) wall(s, c, cy); }
static void vbar(uint32_t s, int cx, int r0, int r1) { for (int r = r0; r <= r1; r++) wall(s, cx, r); }

int main(void) {
  for (uint32_t s = 0; s < N_SCREENS; s++) {
    for (int cx = 0; cx < GRID_W; cx++) { wall(s, cx, 0); wall(s, cx, GRID_H - 1); }   /* N,S border */
    for (int cy = 0; cy < GRID_H; cy++) { wall(s, 0, cy); wall(s, GRID_W - 1, cy); }   /* W,E border */

    /* central cross open: col 10 (all rows) and row 7 (all cols). This also opens
     * the four centre gaps in the borders, connecting all four exits. */
    for (int cy = 0; cy < GRID_H; cy++) open_(s, GRID_W / 2, cy);      /* col 10 */
    for (int cx = 0; cx < GRID_W; cx++) open_(s, cx, GRID_H / 2);      /* row 7  */

    /* interior blocks (avoid row 7 / col 10). Bars only — no rings, so nothing is
     * sealed off. A little per-screen variety to vary the flow fields. */
    hbar(s, 3, 6, 3);          /* top-left   */
    vbar(s, 15, 2, 4);         /* top-right  */
    hbar(s, 2, 6, 10);         /* bottom-left */
    vbar(s, 13, 9, 11);        /* bottom-right, col 13 */
    wall(s, 14, 9); wall(s, 14, 10);
    switch (s % 4) {
      case 0: hbar(s, 6, 7, 2);  break;
      case 1: vbar(s, 14, 5, 6); break;
      case 2: vbar(s, 5, 9, 12); break;
      case 3: hbar(s, 12, 16, 11); break;
    }
  }

  printf("/* GENERATED by tools/gen_map.c (gen.sh) — do not edit by hand.\n");
  printf(" * The initial 4x4 world map, one 20-bit word per screen-row\n");
  printf(" * (GRID_INIT[screen*GRID_H + cy], bit c == column c, 1 = wall).\n");
  printf(" * Borders are solid except a centred one-cell gap per side; the gaps\n");
  printf(" * line up across inner screen edges and the outer wrap. */\n");
  printf("#include \"map.h\"\n\n");
  printf("const uint32_t GRID_INIT[N_SCREENS * GRID_H] = {\n");
  for (uint32_t s = 0; s < N_SCREENS; s++) {
    printf("  /* screen %2u  (sx %u, sy %u) */\n", s, s % SCREENS_X, s / SCREENS_X);
    for (int cy = 0; cy < GRID_H; cy++) {
      printf("  0x%05X,  /* ", g[s][cy]);
      for (int cx = 0; cx < GRID_W; cx++) putchar((g[s][cy] >> cx) & 1u ? '#' : '.');
      printf(" */\n");
    }
  }
  printf("};\n");
  return 0;
}
