/* gen_trig.c — bake the Q14 cosine table and emit it as committed C source.
 *
 * The table depends on no runtime input, so it is build-time data: generated on
 * the host and compiled in, never computed at launch (data-oriented-design:
 * author build-time data in its target representation). gen.sh runs this and
 * writes src/trig_table.c; build.sh and test.sh run gen.sh first so the table is
 * always fresh with respect to N_TRIG / TRIG_ONE in trig.h. */
#include <stdio.h>
#include <math.h>
#include "../src/trig.h"

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

int main(void) {
  printf("/* GENERATED by tools/gen_trig.c — do not edit by hand.\n");
  printf(" * Q14 cosine, %d samples over one full circle. sin is read from the\n", N_TRIG);
  printf(" * same table a quarter-turn over (see trig.h), so there is no sine table. */\n");
  printf("#include \"trig.h\"\n\n");
  printf("const int16_t TRIG_COS[N_TRIG] = {\n");
  for (int i = 0; i < N_TRIG; i++) {
    double a = (2.0 * M_PI * i) / N_TRIG;
    long v = lround(cos(a) * TRIG_ONE);
    if (v > 32767) v = 32767;
    if (v < -32768) v = -32768;
    printf("%ld,", v);
    if ((i & 15) == 15) printf("\n");
  }
  printf("};\n");
  return 0;
}
