/* gen_escape.c — HOST-ONLY. Emits src/escape_table.c (the steer escape table) to
 * stdout. Run from gen.sh, which writes the result into the tree; the file is
 * committed and compiled into the wasm. The table depends only on compile-time
 * geometry, so it is generated here once, not built at runtime. */
#include <stdio.h>
#include "escape_build.h"

int main(void) {
  uint32_t open[N_PATTERNS];
  patterns_build_open(open);
  uint8_t esc[N_PATTERNS * N_DIRS];
  build_escape_table(esc, open);

  printf("/* GENERATED by tools/gen_escape.c (gen.sh) — do not edit by hand.\n");
  printf(" * The steer's nearest-open escape per (pattern, travel). Fully determined\n");
  printf(" * by compile-time geometry, so it is baked here, not built at runtime.\n");
  printf(" * Indexed [pattern*N_DIRS + travel]: bit5 = handedness, bits0-4 = dir,\n");
  printf(" * 0xFF = none. `pattern` is a cell's 4-neighbour wall code (N E S W). */\n");
  printf("#include \"escape_table.h\"\n\n");
  printf("const uint8_t PATTERN_ESCAPE[N_PATTERNS * N_DIRS] = {\n");
  for (uint32_t p = 0; p < N_PATTERNS; p++) {
    printf("  /* pattern %2u  N%u E%u S%u W%u */\n  ",
           p, p & 1u, (p >> 1) & 1u, (p >> 2) & 1u, (p >> 3) & 1u);
    for (uint32_t t = 0; t < N_DIRS; t++) printf("0x%02x,", esc[p * N_DIRS + t]);
    printf("\n");
  }
  printf("};\n");
  return 0;
}
