/* GENERATED by tools/bake_map_assets.mjs — the TOWN map mesh table + group indices.
 * render.c addresses meshes as BASE + offset; the static-map bake places instances. */
#ifndef TANK_MAP_MESH_DATA_H
#define TANK_MAP_MESH_DATA_H
#include <stdint.h>

#define MAP_MESH_COUNT 32
#define MAP_LOD1_OFFSET 16   /* the LOD1 (simplified) of town mesh m is m + MAP_LOD1_OFFSET */
#define MAP_ROAD_BASE 0
#define MAP_ROAD_N 6
#define MAP_BUILD_BASE 6
#define MAP_BUILD_N 8
#define MAP_GRASS_BASE 14
#define MAP_LANDMARK_BASE 15

extern const int8_t   MAP_MESH_VERT[];
extern const uint32_t MAP_MESH_VOFF[MAP_MESH_COUNT];
extern const uint32_t MAP_MESH_VCNT[MAP_MESH_COUNT];
extern const int16_t  MAP_MESH_HZ[MAP_MESH_COUNT];
extern const uint8_t  MAP_ROAD_CANON[MAP_ROAD_N];  /* autotile: per-road canonical connection mask (N=1,E=2,S=4,W=8) */
extern const uint32_t MAP_MESH_VERT_TOTAL;
#endif
